default: &default
  adapter: mysql2
  pool: 25
  timeout: 5000
  database: <%= ENV["MYSQL_DB_NAME"] %>
  host: <%= ENV["MYSQL_HOST"] %>
  port: <%= ENV["MYSQL_PORT"] %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>

development:
  <<: *default
